
import "./globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";
import Provider from '@/components/Provider';
import Loading from "./loading";

import { Inter } from "next/font/google";
import RootContainer from "@/components/shared/containers/root";
import { Suspense } from "react";
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
  weight: "500",
});

const yekanBakh = localFont({
  src: [
    {
      path: "../public/fonts/YekanBakh/YekanBakh-Thin.woff2",
      weight: "100",
    },
    {
      path: "../public/fonts/YekanBakh/YekanBakh-Light.woff2",
      weight: "200",
    },
    {
      path: "../public/fonts/YekanBakh/YekanBakh-Light.woff2",
      weight: "300",
    },
    {
      path: "../public/fonts/YekanBakh/YekanBakh-Regular.woff2",
      weight: "400",
    },
    {
      path: "../public/fonts/YekanBakh/YekanBakh-SemiBold.woff2",
      weight: "500",
    },
    {
      path: "../public/fonts/YekanBakh/YekanBakh-SemiBold.woff2",
      weight: "600",
    },
    {
      path: "../public/fonts/YekanBakh/YekanBakh-Bold.woff2",
      weight: "700",
    },
    {
      path: "../public/fonts/YekanBakh/YekanBakh-ExtraBold.woff2",
      weight: "800",
    },
    {
      path: "../public/fonts/YekanBakh/YekanBakh-Black.woff2",
      weight: "900",
    },
    // fa-numbers
    {
      path: "../public/fonts/YekanBakh/Yekan-Bakh-FaNum-04-Regular.woff",
      weight: "400",
    },
    {
      path: "../public/fonts/YekanBakh/Yekan-Bakh-FaNum-05-Medium.woff",
      weight: "500",
    },
  ],
});

export const metadata: Metadata = {
  title: "Milad Hotel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" dir="rtl">
      <body className={`${inter.variable} ${yekanBakh.className}`}>
      
          <Suspense fallback={<Loading />}>
            <Provider>
              <RootContainer>{children}</RootContainer>
            </Provider>
          </Suspense>
       

      </body>
    </html>
  );
}
