const menuItems = [
  {
    id: 1,
    name: "اسپرسو|ESPRESSO",
    description: "عصاره خالص قهوه با غلظت بالا ",
    price: 57800,
    image: "/images/cafe/menu-items/Espresso.webp",
  },
  {
    id: 2,
    name: "اسپرسو ماکیاتو|ESPRESSO MACCHIATO",
    description: "ترکیب اسپرسو و مقدار کمی شیر و فوم شیر",
    price: 64800,
    image: "/images/cafe/menu-items/Espresso-Macchiato.webp",
  },

  {
    id: 3,
    name: "آمریکانو|AMERICANO",
    description: "ترکیب اسپرسو و آب",
    price: 64800,
    image: "/images/cafe/menu-items/Americano.webp",
  },

  {
    id: 4,
    name: "کاپوچینو|CAPPUCCINO",
    description: "ترکیب اسپرسو و شیر با فوم زیاد",
    price: 72800,
    image: "/images/cafe/menu-items/Cappuccino.webp",
  },

  {
    id: 5,
    name: "لاته|LATTE",
    description: "ترکیب اسپرسو و شیر با فوم کم",
    price: 72800,
    image: "/images/cafe/menu-items/Latte.webp",
  },
  {
    id: 6,
    name: "موکا|MOCHA",
    description: "ترکیب قهوه و شکلات",
    price: 78800,
    image: "/images/cafe/menu-items/Mocha.webp",
  },
  {
    id: 7,
    name: "هات چاکلت|HOT CHOCOLATE​",
    description: "ترکیب شکلات و پودر کاکائو و شیر گرم",
    price: 84800,
    image: "/images/cafe/menu-items/Hot-Chocolate.webp",
  },
  {
    id: 8,
    name: "کارامل ماکیاتو|CARAMEL MACCHIATO",
    description: "ترکیب وانیل و کارامل در کنار شیر و قهوه",
    price: 78800,
    image: "/images/cafe/menu-items/Caramel-Macchiato.webp",
  },
  {
    id: 9,
    name: "قهوه دمی|DAILY BREW",
    description: "قهوه فرانسه",
    price: 64800,
    image: "/images/cafe/menu-items/Daily-Brew.webp",
  },
  {
    id: 10,
    name: "آیس لاته|ICED LATTE",
    description: "ترکیب اسپرسو و شیرسرد کم چرب و یخ",
    price: 89800,
    image: "/images/cafe/menu-items/Iced-Latte.webp",
  },
  {
    id: 11,
    name: "آیس آمریکانو|ICED AMERICANO",
    description: "ترکیب اسپرسو و آب و یخ",
    price: 66800,
    image: "/images/cafe/menu-items/Iced-Americano.webp",
  },
  {
    id: 12,
    name: "موکا سرد|ICED MOCHA",
    description: "ترکیب اسپرسو و شیر سرد و شکلات و یخ",
    price: 89800,
    image: "/images/cafe/menu-items/Iced-Mocha.webp",
  },
  {
    id: 13,
    name: "کاپوچینو سرد|ICED CAPPUCCINO",
    description: "ترکیب اسپرسو و وانیل و شیر و یخ",
    price: 98600,
    image: "/images/cafe/menu-items/Iced-Capppuccino.webp",
  },
  {
    id: 14,
    name: "کاپاچیلو|CAPPACHILLO",
    description: " ترکیب اسپرسو و بستنی وانیلی و یخ",
    price: 98600,
    image: "/images/cafe/menu-items/Cappachillo.webp",
  },
  {
    id: 15,
    name: "موکاچیلو|MOCHACHILLO",
    description: "ترکیب اسپرسو و بستنی وانیلی و شکلات یخ",
    price: 108600,
    image: "/images/cafe/menu-items/Mochachillo.webp",
  },
  {
    id: 16,
    name: "چیلو میوه ای|FRUITCHILLO",
    description: " بستنی انبه یا توت فرنگی یا هلو",
    price: 95600,
    image: "/images/cafe/menu-items/Fruitchillo.webp",
  },
  {
    id: 17,
    name: "شیک ماسالا|MASALA SHAKE",
    description: "ترکیب بستنی و شیر و پودر ماسالا و بیسکوییت",
    price: 87500,
    image: "/images/cafe/menu-items/Masala-Shake.webp",
  },
  {
    id: 18,
    name: "کروسان ساده|CROISSANT",
    description: "نان شیرینی ساده",
    price: 56800,
    image: "/images/cafe/menu-items/Croissant.webp",
  },
  {
    id: 19,
    name: "گاتا|GATA",
    description: "نان شیرینی سنتی ارمنی",
    price: 49800,
    image: "/images/cafe/menu-items/Gata.webp",
  },
  {
    id: 20,
    name: "کیک هویج|CARROT CAKE",
    description: "کیک با طعم هویج همراه خامه",
    price: 68800,
    image: "/images/cafe/menu-items/Carrot-cake.webp",
  },
  {
    id: 21,
    name: "تارت کارامل|CARAMEL TART",
    description: "کیک مخصوص کاراملی",
    price: 82800,
    image: "/images/cafe/menu-items/Caramel-Tart.webp",
  },
  {
    id: 22,
    name: "تارت شکلات فندق|CHOCOLATE HAZELNUT TART",
    description: "کیک شکلاتی مخصوص با دانه های فندق",
    price: 94800,
    image: "/images/cafe/menu-items/Chocolate-Hazelnut-Tart.webp",
  },
  {
    id: 23,
    name: "تیرامیسو|TIRAMISU",
    description: "کیک بستنی ایتالیایی",
    price: 94800,
    image: "/images/cafe/menu-items/Tiramisu.webp",
  },
  {
    id: 24,
    name: "کوکی شکلات دارک|DARK CHOCOLATE COOKIE",
    description: "شیرینی شکلاتی تلخ",
    price: 36800,
    image: "/images/cafe/menu-items/DArk-Chocolate-Cookie.webp",
  },
];

export default menuItems;
